#!/bin/bash

LINES=`wc -l /home/goij/OijpaClock/badjokes.txt | sed -e 's/ .*//'`

rnd=`echo $((1 + RANDOM % $LINES))`

BADJOKE=`sed "${rnd}q;d" /home/goij/OijpaClock/badjokes.txt`

echo "Joke #$rnd: $BADJOKE"

echo $BADJOKE | sudo festival --tts
echo $BADJOKE | sudo espeak -a 150 -p 65 >/dev/null 2>/dev/null
